// a2uigen regenerates the TypeScript A2UI rendering contract from the catalog
// and the shared fixtures.
//
//	go run ./cmd/a2uigen
//
// The demo and Console renderers must agree on component names, closed value
// sets, structural limits and baseline surfaces. Rather than have each restate
// them, both receive a generated copy of the same facts, and `make a2ui-check`
// fails if a copy drifts from the catalog.
//
// Outputs:
//   - demos/aap-chat/client/src/a2ui/generated/{catalog,fixtures}.gen.ts
//   - frontend/src/components/a2ui/generated/{catalog,fixtures}.gen.ts
//     (identical bytes in both renderer trees)
//   - sdk/typescript/src/generated/a2ui.gen.ts
//   - sdk/typescript/test/generated/a2ui-fixtures.gen.ts
//
// The SDK copy carries the same catalog facts without the renderer host contract:
// the SDK hands a third party the surface and the vocabulary to read it, and does
// not dictate how they draw it.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"actweave/backend/internal/a2ui"
	"actweave/backend/internal/a2ui/a2uifixtures"
)

// target is one consumer of the generated contract.
type target struct {
	// catalogPath and fixturesPath are relative to the repository root.
	catalogPath  string
	fixturesPath string
	// renderContract includes the host renderer interfaces (A2UIRenderCtx,
	// A2UIRegistry). Only our own renderers implement them.
	renderContract bool
	// surfaceImport is how the fixtures file reaches the A2UISurface type.
	surfaceImport string
}

var targets = []target{
	{
		catalogPath:    filepath.Join("demos", "aap-chat", "client", "src", "a2ui", "generated", "catalog.gen.ts"),
		fixturesPath:   filepath.Join("demos", "aap-chat", "client", "src", "a2ui", "generated", "fixtures.gen.ts"),
		renderContract: true,
		surfaceImport:  "./catalog.gen",
	},
	{
		catalogPath:    filepath.Join("frontend", "src", "components", "a2ui", "generated", "catalog.gen.ts"),
		fixturesPath:   filepath.Join("frontend", "src", "components", "a2ui", "generated", "fixtures.gen.ts"),
		renderContract: true,
		surfaceImport:  "./catalog.gen",
	},
	{
		catalogPath:   filepath.Join("sdk", "typescript", "src", "generated", "a2ui.gen.ts"),
		fixturesPath:  filepath.Join("sdk", "typescript", "test", "generated", "a2ui-fixtures.gen.ts"),
		surfaceImport: "../../src/generated/a2ui.gen.js",
	},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "a2uigen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	repoRoot, err := resolveRepoRoot()
	if err != nil {
		return err
	}

	count := 0
	for _, target := range targets {
		catalog, err := renderCatalog(target.renderContract)
		if err != nil {
			return err
		}
		fixtures, fixtureCount, err := renderFixtures(target.surfaceImport)
		if err != nil {
			return err
		}
		count = fixtureCount
		if err := writeGenerated(filepath.Join(repoRoot, target.catalogPath), catalog); err != nil {
			return err
		}
		if err := writeGenerated(filepath.Join(repoRoot, target.fixturesPath), fixtures); err != nil {
			return err
		}
	}
	fmt.Printf("a2uigen: %d components, %d fixtures → %d targets\n",
		len(a2ui.CatalogComponentNames()), count, len(targets))
	return nil
}

func writeGenerated(path string, payload []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, payload, 0o644)
}

func resolveRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	// Runs from either the repo root or backend/, matching protocolgen.
	for _, candidate := range []string{cwd, filepath.Dir(cwd)} {
		if _, err := os.Stat(filepath.Join(candidate, "frontend", "package.json")); err == nil {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("cannot locate the repository root from %s", cwd)
}

const generatedHeader = `// Code generated by a2uigen; DO NOT EDIT.
// Source: backend/internal/a2ui/catalogs/standard/v1/catalog.json
`

func renderCatalog(renderContract bool) ([]byte, error) {
	components := a2ui.CatalogComponentNames()
	if len(components) == 0 {
		return nil, fmt.Errorf("catalog exposes no components")
	}
	enums := a2ui.CatalogEnums()
	chartTypes := enums["Chart"]["chartType"]
	valueFormats := enums["Chart"]["valueFormat"]
	if len(chartTypes) == 0 || len(valueFormats) == 0 {
		return nil, fmt.Errorf("catalog Chart is missing chartType or valueFormat")
	}

	var out bytes.Buffer
	out.WriteString(generatedHeader)
	out.WriteString(`
/** Catalog this contract describes. A surface declaring any other catalogId is not ours. */
`)
	fmt.Fprintf(&out, "export const A2UI_CATALOG_ID = %q as const;\n\n", a2ui.CatalogID)
	out.WriteString("/** Content-part version carrying a catalog-conformant surface. */\n")
	fmt.Fprintf(&out, "export const A2UI_SURFACE_VERSION = %q as const;\n\n", a2ui.EnvelopeVersionV1)

	out.WriteString(`/**
 * Structural limits the server enforces. A renderer that also respects them
 * cannot be driven into unbounded work by a surface from another producer.
 */
export const A2UI_LIMITS = {
`)
	fmt.Fprintf(&out, "  maxSurfaceBytes: %d,\n", a2ui.MaxSurfaceBytes)
	fmt.Fprintf(&out, "  maxComponents: %d,\n", a2ui.MaxComponents)
	fmt.Fprintf(&out, "  maxTreeDepth: %d,\n", a2ui.MaxTreeDepth)
	fmt.Fprintf(&out, "  maxChartSeries: %d,\n", a2ui.MaxChartSeries)
	fmt.Fprintf(&out, "  maxChartPoints: %d,\n", a2ui.MaxChartPoints)
	out.WriteString("} as const;\n\n")

	fmt.Fprintf(&out, "/** Id of the single root component every surface must declare. */\nexport const A2UI_ROOT_ID = %q as const;\n\n", a2ui.RootID)

	writeStringUnion(&out, "A2UI_COMPONENT_NAMES", "A2UIComponentName",
		"Every component this catalog defines. Renderers dispatch on exactly these\nnames: no aliases, no case folding.", components)
	writeStringUnion(&out, "A2UI_CHART_TYPES", "A2UIChartType",
		"Chart shapes a surface may ask for.", chartTypes)
	writeStringUnion(&out, "A2UI_VALUE_FORMATS", "A2UIValueFormat",
		"How to format chart values. The surface never carries formatted strings.", valueFormats)

	if err := writeEnums(&out, components, enums); err != nil {
		return nil, err
	}
	writeChildMembers(&out, components)
	out.WriteString(structuralTypes)
	if renderContract {
		out.WriteString(renderContractTypes)
	}
	return out.Bytes(), nil
}

func writeStringUnion(out *bytes.Buffer, constName, typeName, doc string, values []string) {
	out.WriteString("/**\n")
	for _, line := range strings.Split(doc, "\n") {
		fmt.Fprintf(out, " * %s\n", line)
	}
	out.WriteString(" */\n")
	fmt.Fprintf(out, "export const %s = [\n", constName)
	for _, value := range values {
		fmt.Fprintf(out, "  %q,\n", value)
	}
	out.WriteString("] as const;\n\n")
	fmt.Fprintf(out, "export type %s = (typeof %s)[number];\n\n", typeName, constName)
}

// writeEnums emits every closed value set in the catalog, so a renderer can map
// a variant to a class name without inventing a list of its own.
func writeEnums(out *bytes.Buffer, components []string, enums map[string]map[string][]string) error {
	out.WriteString(`/**
 * Closed value sets, by component and property. A value outside these sets never
 * reaches a renderer: the server rejects the surface first.
 */
export const A2UI_ENUMS = {
`)
	for _, component := range components {
		properties := enums[component]
		if len(properties) == 0 {
			continue
		}
		names := make([]string, 0, len(properties))
		for name := range properties {
			names = append(names, name)
		}
		sort.Strings(names)

		fmt.Fprintf(out, "  %s: {\n", component)
		for _, name := range names {
			quoted := make([]string, 0, len(properties[name]))
			for _, value := range properties[name] {
				quoted = append(quoted, fmt.Sprintf("%q", value))
			}
			fmt.Fprintf(out, "    %s: [%s],\n", name, strings.Join(quoted, ", "))
		}
		out.WriteString("  },\n")
	}
	out.WriteString("} as const;\n\n")
	return nil
}

// writeChildMembers emits which members hold child ids, so a renderer can walk
// the graph without keeping its own list of which components are containers.
func writeChildMembers(out *bytes.Buffer, components []string) {
	members := a2ui.CatalogChildMembers()
	out.WriteString(`/**
 * Members through which a component references children, by component name. A
 * component absent from this map is a leaf. Children are always ids: the graph is
 * flat, and a renderer resolves each id against the surface.
 */
export const A2UI_CHILD_MEMBERS: Readonly<
  Partial<Record<A2UIComponentName, readonly { readonly member: string; readonly list: boolean }[]>>
> = {
`)
	for _, component := range components {
		if len(members[component]) == 0 {
			continue
		}
		entries := make([]string, 0, len(members[component]))
		for _, member := range members[component] {
			entries = append(entries,
				fmt.Sprintf("{ member: %q, list: %t }", member.Member, member.List))
		}
		fmt.Fprintf(out, "  %s: [%s],\n", component, strings.Join(entries, ", "))
	}
	out.WriteString("} as const;\n\n")
}

// structuralTypes mirrors surface.schema.json. Component members are reached
// through an index signature rather than a generated per-component interface:
// a renderer resolves every member through the binding-aware helpers anyway, so
// per-component types would describe a shape the renderer never handles directly.
const structuralTypes = `/** A JSON Pointer into the surface dataModel. */
export interface A2UIDataBinding {
  path: string;
}

/** A literal value, or a binding that resolves to one. */
export type A2UIDynamic<T> = T | A2UIDataBinding;

export interface A2UIChartPoint {
  label: string;
  value: number;
}

export interface A2UIChartSeries {
  name?: string;
  points: A2UIChartPoint[];
}

/**
 * One node of the component graph. Children are referenced by id, never nested,
 * so the graph is flat and a renderer walks it from A2UI_ROOT_ID.
 */
export interface A2UIComponentNode {
  id: string;
  component: string;
  [member: string]: unknown;
}

/**
 * The A2UI createSurface payload. surfaceId and catalogId are stamped by the
 * platform, so they are absent on a surface as a model emits it and present on
 * one delivered to a renderer.
 */
export interface A2UISurface {
  surfaceId?: string;
  catalogId?: string;
  components: A2UIComponentNode[];
  dataModel?: unknown;
}

export function isA2UIComponentName(value: string): value is A2UIComponentName {
  return (A2UI_COMPONENT_NAMES as readonly string[]).includes(value);
}

export function isA2UIChartType(value: unknown): value is A2UIChartType {
  return typeof value === "string" && (A2UI_CHART_TYPES as readonly string[]).includes(value);
}
`

// renderContractTypes is the host renderer interface, emitted only for our own
// renderers. A third party reading a surface through the SDK needs the catalog
// vocabulary above, not our dispatch shape.
const renderContractTypes = `
/**
 * What a component renderer is handed. R is the host's output: a markup string
 * in the demo, a VNode in Console.
 *
 * The resolve* methods are the binding-aware read surface: a member may be a
 * literal or a pointer into dataModel, and a renderer must never tell them apart
 * by itself. Both hosts implement them over the same fixtures.
 */
export interface A2UIRenderCtx<R> {
  /** Every component in the surface, by id. Children are ids, not nested nodes. */
  byId: Map<string, A2UIComponentNode>;
  dataModel: unknown;
  /** Depth of the node being rendered, starting at 1 for the root. */
  depth: number;
  resolveString(value: unknown): string;
  resolveBoolean(value: unknown): boolean;
  /** One selection, several, or a binding to either. */
  resolveChoiceValues(value: unknown): string[];
  /** Chart data, inline or bound, with malformed entries dropped. */
  resolveSeries(value: unknown): A2UIChartSeries[];
  /** Renders a child by id, or a placeholder when it cannot be rendered. */
  renderChild(id: string): R;
  /** Placeholder for a component this renderer cannot draw. */
  placeholder(reason: string): R;
}

export type A2UIComponentRenderer<R> = (node: A2UIComponentNode, ctx: A2UIRenderCtx<R>) => R;

/**
 * Dispatch table keyed by exact component name. It is a total record on purpose:
 * a renderer that forgets a catalog component fails to compile rather than
 * silently falling back to a placeholder for a component we do support.
 */
export type A2UIRegistry<R> = Record<A2UIComponentName, A2UIComponentRenderer<R>>;
`

func renderFixtures(surfaceImport string) ([]byte, int, error) {
	fixtures, err := a2uifixtures.All()
	if err != nil {
		return nil, 0, err
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by a2uigen; DO NOT EDIT.\n")
	out.WriteString("// Source: backend/internal/a2ui/a2uifixtures/surfaces\n\n")
	fmt.Fprintf(&out, "import type { A2UISurface } from %q;\n", surfaceImport)
	out.WriteString(`
/**
 * What a renderer must do with a fixture. "renders" surfaces are accepted by the
 * catalog and must draw in full; a "degrades" surface is rejected by the server
 * and exists to pin down graceful degradation for a client whose catalog is
 * older than the sender's.
 */
export type A2UIFixtureExpectation = "renders" | "degrades";

export interface A2UIFixture {
  /** Stable key, shared by both renderers' tests. */
  name: string;
  /** One-line description, used for test and menu labels. */
  title: string;
  expect: A2UIFixtureExpectation;
  /** Why the fixture exists and what to look for when it renders. */
  note: string;
  surface: A2UISurface;
}

/** The shared rendering baselines, in presentation order. */
export const A2UI_FIXTURES: readonly A2UIFixture[] = [
`)
	for _, fixture := range fixtures {
		surface := reindent(string(fixture.Surface), 4)
		out.WriteString("  {\n")
		fmt.Fprintf(&out, "    name: %q,\n", fixture.Name)
		fmt.Fprintf(&out, "    title: %q,\n", fixture.Title)
		fmt.Fprintf(&out, "    expect: %q,\n", string(fixture.Expect))
		fmt.Fprintf(&out, "    note: %q,\n", fixture.Note)
		fmt.Fprintf(&out, "    surface: %s,\n", surface)
		out.WriteString("  },\n")
	}
	out.WriteString(`];

export const A2UI_FIXTURES_BY_NAME: Readonly<Record<string, A2UIFixture>> = Object.freeze(
  Object.fromEntries(A2UI_FIXTURES.map((fixture) => [fixture.name, fixture])),
);
`)
	return out.Bytes(), len(fixtures), nil
}

// reindent shifts a fixture surface to sit inside the generated array while
// keeping the authored line breaks. Re-serializing instead would spread every
// small object over five lines and make the generated file unreviewable, so the
// source text is moved rather than rewritten. The shift is derived from the
// closing brace, which sits at the surface's own indentation in the source file.
func reindent(raw string, indent int) string {
	lines := strings.Split(raw, "\n")
	if len(lines) < 2 {
		return raw
	}
	last := lines[len(lines)-1]
	shift := indent - (len(last) - len(strings.TrimLeft(last, " ")))
	for index := 1; index < len(lines); index++ {
		switch {
		case shift > 0:
			lines[index] = strings.Repeat(" ", shift) + lines[index]
		case shift < 0:
			lines[index] = strings.TrimPrefix(lines[index], strings.Repeat(" ", -shift))
		}
	}
	return strings.Join(lines, "\n")
}
